# Generated by Django 4.1.3 on 2022-11-06 18:14

import colorfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_alter_entity_options_document_footprint_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="entity",
            name="color",
            field=colorfield.fields.ColorField(default="#FF0000", image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name="document",
            name="stored_id",
            field=models.UUIDField(default=uuid.UUID("175e1230-2ae5-4eb0-aa57-a35a0f82b860")),
        ),
    ]
