# Generated by Django 4.1.3 on 2022-12-03 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_language_alter_entity_options_document_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="mime_type",
            field=models.CharField(default="application/octet-stream", max_length=50),
        ),
        migrations.AlterField(
            model_name="document",
            name="stored_id",
            field=models.UUIDField(default=uuid.UUID("f71f1f5e-68d5-446c-a9e0-856623df978d")),
        ),
    ]
